application: zombie-run-game-server
version: 1
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /game
  static_files: static/game.html
  upload: static/game.html
  login: required
- url: /js
  static_dir: static/js
- url: /res
  static_dir: static/res
- url: /.*
  script: main.py